### ISSUE TITLE
Program asked me to report issue

### ISSUE THREAD

**Issue by JimCoene** [RealFaviconGenerator/realfavicongenerator#107]
program could not handle my logo
![savasananowsquare](https://cloud.githubusercontent.com/assets/9644957/4969009/e947ca12-6853-11e4-9d69-40b358ad29d7.jpg)

**Comment by phbernard** [comment]
Hum, not good.

Could you repost your logo? The link is broken in your original post.

**Comment by JimCoene** [comment]
![savasananowsquaresmall](https://cloud.githubusercontent.com/assets/9644957/4969291/d9471f0c-685b-11e4-9817-7e2185d46f84.jpg)

**Comment by JimCoene** [comment]
thanks

**Comment by phbernard** [comment]
I can't reproduce the issue on my side: it works in my Chrome.

What do you use (browser/OS)? Could you try with another browser?

What is the original name of your picture? GitHub renamed it to `d9471f0c-685b-11e4-9817-7e2185d46f84.jpg`, I guess you didn't name your picture that way.

May be related to #96

**Comment by JimCoene** [comment]
The original name was SavasanaNowSquareSmall2.jpg
The first 2 parts look great, but the bottom has the error. Here is a screen shot
![image](https://cloud.githubusercontent.com/assets/9644957/4970125/bfc12cf8-6879-11e4-8a84-a45dffe7fe53.png)

**Comment by phbernard** [comment]
Oh, ok.

Well, I'm really not lucky here, it worked again:

![image](https://cloud.githubusercontent.com/assets/423852/4972834/09e7e636-68b2-11e4-8761-108af8e73c89.png)

I need to investigate this further.

**Comment by JimCoene** [comment]
By the way, I was doing it on chrome. I also tried Firefox. I have even un-installed and re-installed the plugin and get the same results. Thanks.

**Comment by phbernard** [comment]
I found the issue! Your last message made me realize you were using the plugin (and not RFG directly). There was an issue when the picture was not a PNG file _and_ the service was invoked with the API.

Thank you for having taken time to report this bug. It has been here for long but you are the first to notify me.

Fixed and deployed a minute. Please give it another try, it should work now.

**Comment by JimCoene** [comment]
Yes, thanks. Now I don't get the compression error. But when I view my website on chrome, I don't see the logo. It shows up only on the one I'm logged onto wordpress with. I gave it over an hour to propagate.
![image](https://cloud.githubusercontent.com/assets/9644957/4980044/672865f6-68fc-11e4-9b13-42dfef20790f.png)

**Comment by phbernard** [comment]
Sorry for the late answer :(

Browsers tend to cache icons. So yes, what you observe is not strange. Does it work now? Did you have the opportunity to try with a browser you don't regularly use? (so its cache does not contain anything about your site under dev)

As the compression issue is solved, I close this issue. Yet, don't hesitate to reply to it or open a new one if necessary.

**Comment by JimCoene** [comment]
Its still show up with the Wordpress icon when I vistit my site on Chrome,
but on other browsers it looks good, so it must be cashed in there
somewhere. So i assume it will be ok when others look. Thanks.
